import type { Certification, LearningPath } from '../lib/types'

export const CERTIFICATIONS: Certification[] = [
  {
    id: 'cma',
    title: 'Certified Miau Analyst',
    description: 'Master financial analysis — DCF, WACC, comps, LBO, portfolio theory, and risk. Equivalent to the first year of a CFA program, but with more cat jokes.',
    icon: '🎓',
    color: '#00ff88',
    difficulty: 'advanced',
    estimatedHours: 40,
    courseIds: ['getting-started', 'market-data-basics', 'market-data-advanced', 'fundamentals', 'investment-banking', 'portfolio-management', 'risk-analytics', 'technical-analysis', 'derivatives', 'macro-economics', 'financial-modeling', 'corporate-finance', 'accounting-for-investors', 'fixed-income', 'portfolio-theory-advanced', 'quantitative-risk', 'financial-history', 'business-cycles'],
    skills: ['Financial Statement Analysis', 'DCF & Valuation', 'Portfolio Theory', 'Risk Management', 'Technical Analysis', 'Market Data Mastery', 'Derivatives Pricing', 'Macro Analysis', 'Financial Modeling', 'Corporate Finance', 'Accounting', 'Fixed Income'],
    badge: 'CMA',
  },
  {
    id: 'cmt',
    title: 'Certified Miau Trader',
    description: 'Learn institutional-grade trading — order types, execution strategies, paper trading, and live market operations. Become a terminal-native trader.',
    icon: '📈',
    color: '#ff8800',
    difficulty: 'intermediate',
    estimatedHours: 30,
    courseIds: ['getting-started', 'market-data-basics', 'trading-orders', 'paper-trading', 'technical-analysis', 'strategies', 'risk-analytics', 'behavioral-finance', 'crypto-blockchain', 'commodities', 'forex-trading', 'market-microstructure', 'backtesting', 'financial-news-literacy', 'tax-optimization'],
    skills: ['Order Execution', 'Paper Trading', 'Strategy Backtesting', 'Technical Indicators', 'Position Sizing', 'Risk Controls', 'Trading Psychology', 'Crypto Markets', 'Commodities', 'Forex', 'Market Microstructure', 'Tax Optimization'],
    badge: 'CMT',
  },
  {
    id: 'cdefi',
    title: 'Certified DeFi Specialist',
    description: 'From wallet basics to protocol composability. Navigate DeFi, Web3, and on-chain finance with confidence.',
    icon: '🔗',
    color: '#aa66ff',
    difficulty: 'intermediate',
    estimatedHours: 25,
    courseIds: ['getting-started', 'defi-web3', 'global-markets', 'platform-features', 'advanced-analytics', 'crypto-blockchain', 'defi-advanced-protocols', 'real-world-assets', 'layer2-scaling', 'mev-blockchain-trading', 'daos-governance', 'nfts-digital-assets', 'regenerative-finance'],
    skills: ['Wallet Management', 'DeFi Protocols', 'Yield Analysis', 'Web3 Security', 'Cross-Chain Operations', 'Gas Optimization', 'Crypto Trading', 'On-Chain Analysis', 'Layer 2', 'MEV', 'DAOs', 'RWA Tokenization'],
    badge: 'CDS',
  },
  {
    id: 'cqf',
    title: 'Certified Quantitative Analyst',
    description: 'Quantitative finance meets cat intuition. Factor models, Monte Carlo, options pricing, and statistical arbitrage.',
    icon: '🧮',
    color: '#00aaff',
    difficulty: 'advanced',
    estimatedHours: 45,
    courseIds: ['getting-started', 'market-data-advanced', 'strategies', 'advanced-analytics', 'risk-analytics', 'portfolio-management', 'ai-advisor', 'investment-banking', 'derivatives', 'macro-economics', 'machine-learning-finance', 'time-series-analysis', 'backtesting', 'options-advanced', 'portfolio-theory-advanced', 'quantitative-risk', 'python-for-finance'],
    skills: ['Quantitative Modeling', 'Statistical Analysis', 'Options Pricing', 'Factor Models', 'Monte Carlo Simulation', 'Algorithmic Trading', 'Derivatives Strategies', 'Macro Modeling', 'Machine Learning', 'Time Series', 'Backtesting', 'Portfolio Theory'],
    badge: 'CQF',
  },
  {
    id: 'cbag',
    title: 'Certified Miau Bagholder',
    description: 'You bought the top. You held. You are still here. Honor the diamond hands with the most prestigious (and ironic) certification in finance.',
    icon: '🦍',
    color: '#ff4444',
    difficulty: 'beginner',
    estimatedHours: 5,
    courseIds: ['getting-started', 'paper-trading', 'social-features'],
    skills: ['Diamond Hands', 'Cope Management', 'Hopium Analysis', 'Bag Averaging', 'Mental Accounting', 'Loss Acceptance Therapy'],
    badge: 'BAG',
  },
  {
    id: 'cesg',
    title: 'Certified ESG Analyst',
    description: 'Sustainable and green finance — carbon tracking, ESG scores, impact investing, and green bonds.',
    icon: '🌿',
    color: '#44cc44',
    difficulty: 'intermediate',
    estimatedHours: 20,
    courseIds: ['getting-started', 'esg-sustainability', 'global-markets', 'fundamentals', 'platform-features', 'macro-economics', 'sustainable-investing', 'regenerative-finance', 'regulation-compliance', 'monetary-theory-policy', 'business-cycles'],
    skills: ['ESG Scoring', 'Carbon Footprint Analysis', 'Green Bond Valuation', 'Impact Reporting', 'Regulatory Compliance', 'Sustainability Metrics', 'Climate Risk Modeling', 'ReFi', 'Impact Investing', 'Monetary Policy'],
    badge: 'CESG',
  },
  {
    id: 'cai',
    title: 'Certified AI Finance Specialist',
    description: 'Leverage AI for financial analysis — sentiment analysis, AI advisor, automated strategy generation, and NLP for markets.',
    icon: '🤖',
    color: '#ff66aa',
    difficulty: 'advanced',
    estimatedHours: 35,
    courseIds: ['getting-started', 'ai-advisor', 'strategies', 'advanced-analytics', 'market-data-advanced', 'platform-features', 'behavioral-finance', 'machine-learning-finance', 'alternative-data', 'data-viz-finance', 'python-for-finance', 'cybersecurity-finance', 'cloud-devops-finance'],
    skills: ['AI Prompt Engineering for Finance', 'Sentiment Analysis', 'Automated Strategy Generation', 'NLP for Markets', 'AI Risk Assessment', 'Model Evaluation', 'AI Ethics in Finance', 'Machine Learning', 'Alternative Data', 'Data Visualization'],
    badge: 'CAI',
  },
  {
    id: 'cpm',
    title: 'Certified Portfolio Manager',
    description: 'Manage complete portfolio lifecycles — asset allocation, risk parity, wealth management, estate planning, and retirement. From accumulation to distribution, the cat manages it all.',
    icon: '💼',
    color: '#ffcc00',
    difficulty: 'intermediate',
    estimatedHours: 25,
    courseIds: ['portfolio-theory-advanced', 'asset-allocation', 'risk-parity', 'wealth-management', 'estate-planning', 'retirement-planning', 'financial-planning', 'tax-optimization'],
    skills: ['Portfolio Theory', 'Asset Allocation', 'Risk Parity', 'Wealth Management', 'Estate Planning', 'Retirement Planning', 'Financial Planning', 'Tax Optimization'],
    badge: 'CPM',
  },
  {
    id: 'caas',
    title: 'Certified Alternative Assets Specialist',
    description: 'Master non-traditional assets — real estate, art, commodities, agriculture, structured products, convertibles, music royalties, and the space economy. The cat diversifies beyond stocks and bonds.',
    icon: '🏛️',
    color: '#dd8833',
    difficulty: 'advanced',
    estimatedHours: 20,
    courseIds: ['real-estate', 'art-and-collectibles', 'commodities', 'agriculture-finance', 'structured-products', 'convertibles', 'music-royalties', 'space-economy'],
    skills: ['Real Estate Valuation', 'Art Market Analysis', 'Commodity Trading', 'Agriculture Finance', 'Structured Products', 'Convertible Bonds', 'Intangible Asset Valuation', 'Space Economy'],
    badge: 'CAAS',
  },
  {
    id: 'cat',
    title: 'Certified Advanced Trader',
    description: 'Institutional-grade trading strategies — arbitrage, execution algorithms, momentum, crypto derivatives, tail risk hedging, and factor investing. The cat trades circles around Bloomberg terminals.',
    icon: '📈',
    color: '#ff4444',
    difficulty: 'advanced',
    estimatedHours: 25,
    courseIds: ['arbitrage-strategies', 'execution-algorithms', 'momentum-trading', 'crypto-derivatives', 'tail-risk', 'etfs-deep-dive', 'dividend-investing', 'growth-investing', 'value-investing', 'factor-investing'],
    skills: ['Arbitrage Strategies', 'Execution Algorithms', 'Momentum Trading', 'Crypto Derivatives', 'Tail Risk Hedging', 'ETF Analysis', 'Factor Investing', 'Dividend Analysis', 'Growth/Value Investing'],
    badge: 'CAT',
  },
  {
    id: 'cdes',
    title: 'Certified Digital Economy Specialist',
    description: 'Navigate the frontier of digital finance — tokenomics, DePIN, SocialFi, cleantech, healthcare finance, Islamic finance, and small business economics. The cat goes where finance meets the future.',
    icon: '🌐',
    color: '#44aaff',
    difficulty: 'intermediate',
    estimatedHours: 15,
    courseIds: ['tokenomics', 'depin', 'socialfi', 'cleantech-finance', 'healthcare-finance', 'islamic-finance', 'small-business-finance'],
    skills: ['Tokenomics Design', 'DePIN Infrastructure', 'SocialFi', 'CleanTech Finance', 'Healthcare Finance', 'Islamic Finance', 'Small Business Finance'],
    badge: 'CDES',
  },
  {
    id: 'cmsm',
    title: 'Certified Miau Shell Maniac 🏆',
    description: 'Better than an MBA (the cats said so). The ultimate terminal finance certification — master every command, model, and API. Graduate as a Certified Miau Shell Maniac. The flagship cert.',
    icon: '🎓',
    color: '#ff66ff',
    difficulty: 'advanced',
    estimatedHours: 8,
    courseIds: ['miau-shell-maniac'],
    skills: ['Terminal Speed-Finance', 'World Map Navigation', 'Valuation Modeling (DCF/WACC/Comps/LBO)', 'DeFi Protocol Mastery', 'Developer Platform & APIs', 'Final Exam Execution'],
    badge: 'CMSM',
  },
]

export const LEARNING_PATHS: LearningPath[] = [
  {
    id: 'retail-investor',
    title: 'Retail Investor Track',
    description: 'From zero to confident self-directed investor. Learn to research stocks, place orders, manage a portfolio, and avoid the most common mistakes.',
    icon: '🐟',
    color: '#00ff88',
    role: 'Self-Directed Investor',
    estimatedHours: 50,
    stages: [
      { title: 'Foundation', description: 'Get comfortable with the terminal and basic market concepts.', courseIds: ['getting-started', 'market-data-basics', 'behavioral-finance', 'personal-finance', 'financial-news-literacy'] },
      { title: 'Trading', description: 'Learn to place orders and execute trades.', courseIds: ['trading-orders', 'paper-trading', 'crypto-blockchain', 'forex-trading', 'commodities'] },
      { title: 'Analysis', description: 'Analyze markets with technical and fundamental tools.', courseIds: ['technical-analysis', 'fundamentals', 'macro-economics', 'accounting-for-investors', 'financial-history'] },
      { title: 'Portfolio', description: 'Build and manage a diversified portfolio.', courseIds: ['portfolio-management', 'risk-analytics', 'derivatives', 'tax-optimization', 'insurance'] },
    ],
  },
  {
    id: 'quant-dev',
    title: 'Quantitative Developer Track',
    description: 'Build algorithmic trading strategies, backtest them, and deploy to live markets. Python + Miau Finance = superpowers.',
    icon: '⚙️',
    color: '#00aaff',
    role: 'Quant Developer',
    estimatedHours: 60,
    stages: [
      { title: 'Terminal Fluency', description: 'Master the terminal and market data.', courseIds: ['getting-started', 'market-data-advanced', 'behavioral-finance', 'git-finance', 'sql-finance'] },
      { title: 'Strategy Development', description: 'Build and backtest strategies.', courseIds: ['strategies', 'paper-trading', 'derivatives', 'python-for-finance', 'backtesting'] },
      { title: 'Advanced Analytics', description: 'Apply quantitative models and risk frameworks.', courseIds: ['advanced-analytics', 'risk-analytics', 'macro-economics', 'time-series-analysis', 'machine-learning-finance'] },
      { title: 'AI & Automation', description: 'Integrate AI for automated decision-making.', courseIds: ['ai-advisor', 'investment-banking', 'crypto-blockchain', 'alternative-data', 'cloud-devops-finance'] },
    ],
  },
  {
    id: 'defi-native',
    title: 'DeFi Native Track',
    description: 'Go from "what is a wallet" to yield farming, liquidity provision, and cross-chain arbitrage. On-chain, self-custodied, cat-approved.',
    icon: '⛓️',
    color: '#aa66ff',
    role: 'DeFi Power User',
    estimatedHours: 25,
    stages: [
      { title: 'Web3 Foundations', description: 'Wallets, gas, and basic DeFi concepts.', courseIds: ['getting-started', 'defi-web3', 'crypto-blockchain', 'cybersecurity-finance'] },
      { title: 'Global Markets', description: 'Understand how DeFi connects to global finance.', courseIds: ['global-markets', 'platform-features', 'macro-economics', 'real-world-assets'] },
      { title: 'Risk & Yield', description: 'Analyze DeFi risks and optimize yields.', courseIds: ['risk-analytics', 'advanced-analytics', 'behavioral-finance', 'mev-blockchain-trading'] },
      { title: 'Advanced Strategies', description: 'Build sophisticated DeFi strategies.', courseIds: ['strategies', 'esg-sustainability', 'derivatives', 'defi-advanced-protocols', 'daos-governance', 'nfts-digital-assets', 'layer2-scaling', 'regenerative-finance'] },
    ],
  },
  {
    id: 'finance-professional',
    title: 'Finance Professional Track',
    description: 'Designed for analysts, associates, and finance pros transitioning to the terminal. Covers the full Miau Finance enterprise toolkit.',
    icon: '💼',
    color: '#ff8800',
    role: 'Finance Professional',
    estimatedHours: 70,
    stages: [
      { title: 'Core Platform', description: 'Terminal, platform features, and market data.', courseIds: ['getting-started', 'platform-features', 'market-data-basics', 'professional-dev', 'career-in-finance'] },
      { title: 'Valuation & Analysis', description: 'Full IB toolkit and fundamentals.', courseIds: ['investment-banking', 'fundamentals', 'market-data-advanced', 'derivatives', 'financial-modeling', 'accounting-for-investors', 'mergers-and-acquisitions', 'private-equity', 'ipos-and-spacs'] },
      { title: 'Portfolio & Risk', description: 'Institutional portfolio and risk management.', courseIds: ['portfolio-management', 'risk-analytics', 'technical-analysis', 'macro-economics', 'corporate-finance', 'fixed-income', 'hedge-funds', 'banking-institutions'] },
      { title: 'Advanced Tools', description: 'Broker APIs, billing, and social features.', courseIds: ['brokers-apis', 'billing-admin', 'social-features', 'ai-advisor', 'regulation-compliance', 'data-viz-finance', 'emerging-markets'] },
    ],
  },
  {
    id: 'esg-cat-prof',
    title: 'ESG CAT Prof. Dr, Prof. Tuna',
    description: 'The most comprehensive ESG learning path on the planet. Prof. Dr. Tuna (PhD in Climatology, MBA in Sustainable Finance, LLD in Cat Law) guides you through climate risk, carbon markets, ESG reporting, circular economy, blue finance, biodiversity, and regenerative finance. Earn your fins in sustainable investing.',
    icon: '🐟',
    color: '#00dd88',
    role: 'ESG Cat Professor',
    estimatedHours: 80,
    stages: [
      {
        title: 'ESG Foundations — Prof. Tuna\'s Intro to Saving the Planet',
        description: 'The cat explains why your portfolio is warming the planet and what to do about it.',
        courseIds: ['getting-started', 'esg-sustainability', 'professional-dev', 'financial-news-literacy', 'behavioral-finance'],
      },
      {
        title: 'Climate Science for Financers',
        description: 'Physical risk, transition risk, carbon accounting — Prof. Tuna has a PhD in this.',
        courseIds: ['climate-risk', 'macro-economics', 'monetary-theory-policy', 'business-cycles'],
      },
      {
        title: 'Carbon Markets & Emissions Trading',
        description: 'EU ETS, voluntary carbon markets, offset quality, carbon credits trading.',
        courseIds: ['climate-risk', 'global-markets', 'commodities', 'esg-sustainability'],
      },
      {
        title: 'ESG Reporting & Disclosure Frameworks',
        description: 'SASB, TCFD, GRI, EU Taxonomy, ISSB — Prof. Tuna reads 500-page standards so you don\'t have to.',
        courseIds: ['esg-reporting', 'regulation-compliance', 'accounting-for-investors'],
      },
      {
        title: 'Sustainable & Impact Investing',
        description: 'Green bonds, impact funds, SDG alignment, thematic investing.',
        courseIds: ['sustainable-investing', 'esg-sustainability', 'fundamentals', 'platform-features'],
      },
      {
        title: 'Circular Economy & Blue Finance',
        description: 'Waste-to-value, ocean finance, biodiversity, TNFD — Prof. Tuna keeps the ocean clean.',
        courseIds: ['circular-economy', 'esg-reporting', 'regenerative-finance'],
      },
      {
        title: 'Regenerative Finance & Nature-Based Solutions',
        description: 'ReFi, carbon sequestration, natural capital, ecosystem services.',
        courseIds: ['regenerative-finance', 'climate-risk', 'circular-economy', 'sustainable-investing'],
      },
      {
        title: 'ESG Data, Analytics & Tools',
        description: 'ESG scoring, data quality, alternative data for sustainability, climate analytics.',
        courseIds: ['advanced-analytics', 'alternative-data', 'data-viz-finance', 'platform-features'],
      },
      {
        title: 'Green Economy & Policy',
        description: 'Green industrial policy, carbon border taxes, net-zero regulation, green subsidies.',
        courseIds: ['macro-economics', 'monetary-theory-policy', 'global-markets', 'emerging-markets', 'regulation-compliance'],
      },
      {
        title: 'ESG Capstone — Prof. Tuna\'s Final Exam',
        description: 'Build a net-zero portfolio, write a TCFD report, design a carbon credit strategy. Pass and earn the Prof. Tuna seal of approval.',
        courseIds: ['portfolio-management', 'risk-analytics', 'professional-dev', 'career-in-finance'],
      },
    ],
  },
  {
    id: 'esg-sustainability',
    title: 'ESG & Sustainable Finance Track',
    description: 'Build expertise in sustainable finance — carbon markets, ESG ratings, green bonds, and impact measurement.',
    icon: '🌍',
    color: '#44cc44',
    role: 'ESG Analyst',
    estimatedHours: 35,
    stages: [
      { title: 'ESG Foundations', description: 'Learn ESG basics and sustainability frameworks.', courseIds: ['getting-started', 'esg-sustainability', 'professional-dev', 'financial-news-literacy'] },
      { title: 'Global Context', description: 'Understand global markets and sustainability.', courseIds: ['global-markets', 'fundamentals', 'macro-economics', 'monetary-theory-policy', 'business-cycles'] },
      { title: 'Tools & Reporting', description: 'Use platform tools for ESG analysis.', courseIds: ['platform-features', 'advanced-analytics', 'behavioral-finance', 'sustainable-investing', 'regenerative-finance', 'regulation-compliance', 'data-viz-finance'] },
    ],
  },
]
