import type { Course } from '../lib/types'

export const portfolioTheory: Course = {
  id: 'portfolio-theory-advanced',
  slug: 'portfolio-theory-advanced',
  title: 'Portfolio Theory Advanced',
  description: 'CAPM, APT, factor investing, and risk parity — the cat optimizes between risk and tuna rewards.',
  category: 'Investing',
  difficulty: 'advanced',
  icon: '📊',
  lessonCount: 4,
  estimatedMinutes: 20,
  lessons: [
    {
      id: 'portfolio-capm',
      slug: 'capital-asset-pricing-model',
      title: 'Capital Asset Pricing Model',
      description: 'Beta, alpha, and the security market line.',
      commands: ['capm', 'capm calculate'],
      steps: [
        { instruction: 'Calculate CAPM for a stock: `capm calculate --ticker TSLA --market SPY --risk-free 4.5`', command: 'capm calculate --ticker TSLA --market SPY --risk-free 4.5', expectedOutput: 'CAPM: beta=1.85, expected return=14.8%, alpha=-2.3%' },
        { instruction: 'CAPM describes the relationship between systematic risk and expected return.' },
        { instruction: 'The cat\'s beta to tuna is 3.0 — highly correlated, very volatile.' },
      ],
      quiz: [
        { question: 'What does beta measure in CAPM?', options: ['Sensitivity of a stock to overall market movements', 'The expected return of a stock', 'The risk-free rate', 'The alpha generated by a manager'], correctIndex: 0, explanation: 'Beta measures how much a stock\'s returns move relative to the overall market — a beta of 1.5 means 50% more volatility.' },
      ],
    },
    {
      id: 'portfolio-apt',
      slug: 'arbitrage-pricing-theory',
      title: 'Arbitrage Pricing Theory',
      description: 'Multi-factor risk models.',
      commands: ['apt', 'apt factor'],
      steps: [
        { instruction: 'Run APT factor decomposition: `apt factor --ticker AAPL --factors market,size,value,momentum`', command: 'apt factor --ticker AAPL --factors market,size,value,momentum', expectedOutput: 'APT factor loadings: market 1.02, size -0.34, value -0.56, momentum 0.41' },
        { instruction: 'APT allows multiple risk factors instead of just one like CAPM.' },
        { instruction: 'The cat\'s APT factors: tuna supply, sunbeam availability, nap duration.' },
      ],
      quiz: [
        { question: 'How does APT differ from CAPM?', options: ['APT uses multiple factors to explain returns, not just market beta', 'APT is simpler than CAPM', 'APT only works for bonds', 'APT ignores systematic risk'], correctIndex: 0, explanation: 'APT is a multi-factor model that explains asset returns through several macroeconomic or market factors rather than just one.' },
      ],
    },
    {
      id: 'portfolio-factor',
      slug: 'factor-investing',
      title: 'Factor Investing',
      description: 'Value, momentum, size, quality, low volatility.',
      commands: ['factor', 'factor exposure'],
      steps: [
        { instruction: 'Check factor exposure of a portfolio: `factor exposure --portfolio my-portfolio --factors value,momentum,quality,size,volatility`', command: 'factor exposure --portfolio my-portfolio --factors value,momentum,quality,size,volatility', expectedOutput: 'Factor exposure: value 0.23, momentum 0.45, quality 0.32, size -0.12, volatility -0.21' },
        { instruction: 'Factor investing targets specific drivers of return.' },
        { instruction: 'The cat\'s highest factor loading is "cuteness" — historically a strong performer.' },
      ],
      quiz: [
        { question: 'What is factor investing?', options: ['Targeting specific risk factors that explain returns and premiums', 'Diversifying across all available stocks', 'Timing the market based on technical indicators', 'Investing only in index funds'], correctIndex: 0, explanation: 'Factor investing deliberately targets specific factors like value or momentum that historically have generated excess returns.' },
      ],
    },
    {
      id: 'portfolio-parity',
      slug: 'risk-parity-portfolios',
      title: 'Risk Parity',
      description: 'Equal risk contribution across assets.',
      commands: ['risk-parity', 'risk-parity optimize'],
      steps: [
        { instruction: 'Optimize a risk parity portfolio: `risk-parity optimize --assets bonds,stocks,commodities,gold --target-vol 12`', command: 'risk-parity optimize --assets bonds,stocks,commodities,gold --target-vol 12', expectedOutput: 'Risk parity weights: bonds 45%, stocks 15%, commodities 20%, gold 20% — expected vol 12.1%' },
        { instruction: 'Risk parity allocates based on risk contribution, not capital.' },
        { instruction: 'The cat\'s risk parity portfolio: 50% tuna, 50% nap — perfectly balanced.' },
      ],
      quiz: [
        { question: 'What is the core idea of risk parity?', options: ['Each asset class contributes equally to portfolio risk', 'All assets should have equal weight', 'Risk should be eliminated entirely', 'Only low-risk assets should be held'], correctIndex: 0, explanation: 'Risk parity constructs portfolios where each asset class contributes roughly the same amount of total portfolio risk.' },
      ],
    },
  ],
}
