apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  labels:
    app: miau-finance
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@miau.finance
    privateKeySecretRef:
      name: letsencrypt-prod-account-key
    solvers:
      - http01:
          ingress:
            class: nginx
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  labels:
    app: miau-finance
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: admin@miau.finance
    privateKeySecretRef:
      name: letsencrypt-staging-account-key
    solvers:
      - http01:
          ingress:
            class: nginx
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: miau-finance-tls
  namespace: miau-finance
  labels:
    app: miau-finance
spec:
  secretName: miau-finance-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: app.miau.finance
  dnsNames:
    - app.miau.finance
    - api.miau.finance
