#!/usr/bin/env bash
set -euo pipefail

# Miau Finance — Quick Install Script
# Usage: curl -fsSL https://raw.githubusercontent.com/LuZziD/cat-finance-analytics-shell-miau/main/scripts/install.sh | bash
# Requirements: Docker 24+, Docker Compose v2, Git

MIAU_VERSION="v1.0.0"
REPO="https://github.com/LuZziD/cat-finance-analytics-shell-miau.git"
INSTALL_DIR="${MIAU_DIR:-$HOME/miau-finance}"

GREEN='\033[0;32m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

check_deps() {
  if ! command -v docker &>/dev/null; then
    echo -e "${RED}Error: Docker is required. Install it first:${NC}"
    echo "  https://docs.docker.com/engine/install/"
    exit 1
  fi
  if ! docker compose version &>/dev/null; then
    echo -e "${RED}Error: Docker Compose v2 is required.${NC}"
    exit 1
  fi
  if ! command -v git &>/dev/null; then
    echo -e "${YELLOW}Warning: Git not found. Will use curl to download.${NC}"
    USE_CURL=1
  fi
}

clone_repo() {
  echo -e "${CYAN}🐱 Installing Miau Finance ${MIAU_VERSION}...${NC}"
  if [ -d "$INSTALL_DIR" ]; then
    echo -e "${YELLOW}Directory $INSTALL_DIR already exists. Pulling latest...${NC}"
    cd "$INSTALL_DIR" && git pull
  else
    if [ "${USE_CURL:-0}" = "1" ]; then
      curl -fsSL "https://github.com/LuZziD/cat-finance-analytics-shell-miau/archive/refs/heads/main.tar.gz" | tar xz
      mv cat-finance-analytics-shell-miau-main "$INSTALL_DIR"
    else
      git clone --depth 1 --branch main "$REPO" "$INSTALL_DIR"
    fi
  fi
  cd "$INSTALL_DIR"
}

setup_env() {
  if [ ! -f .env ]; then
    echo -e "${CYAN}Creating .env with secure defaults...${NC}"
    cat > .env << ENVEOF
# Miau Finance — Environment Configuration
# Generated by install.sh on $(date)

# Secrets (auto-generated)
JWT_SECRET_KEY=$(openssl rand -hex 32 2>/dev/null || python3 -c "import secrets; print(secrets.token_hex(32))")
POSTGRES_PASSWORD=$(openssl rand -hex 16 2>/dev/null || python3 -c "import secrets; print(secrets.token_hex(16))")
REDIS_PASSWORD=$(openssl rand -hex 16 2>/dev/null || python3 -c "import secrets; print(secrets.token_hex(16))")
MINIO_ROOT_PASSWORD=$(openssl rand -hex 16 2>/dev/null || python3 -c "import secrets; print(secrets.token_hex(16))")
SUPERSET_SECRET_KEY=$(openssl rand -hex 32 2>/dev/null || python3 -c "import secrets; print(secrets.token_hex(32))")
SUPERSET_ADMIN_PASSWORD=$(openssl rand -hex 12 2>/dev/null || python3 -c "import secrets; print(secrets.token_hex(12))")
GRAFANA_PASSWORD=$(openssl rand -hex 12 2>/dev/null || python3 -c "import secrets; print(secrets.token_hex(12))")
AIRFLOW_FERNET_KEY=$(python3 -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())" 2>/dev/null || openssl rand -base64 32)

# Database
DATABASE_URL=postgresql+asyncpg://miau:${POSTGRES_PASSWORD}@postgres:5432/miau
DATABASE_URL_SYNC=postgresql+psycopg2://miau:${POSTGRES_PASSWORD}@postgres:5432/miau

# Redis
REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379/0

# MinIO
MINIO_ROOT_USER=miau
MINIO_ENDPOINT=http://minio:9000

# CORS
CORS_ORIGINS=http://localhost:5173,http://localhost:3000

# Demo — generated securely at first start (V7-001/C1: no hardcoded credentials)
DEMO_USERNAME=$(openssl rand -hex 4)
DEMO_PASSWORD=$(openssl rand -base64 12 | tr -d '/+=')
ENVEOF
    echo -e "${GREEN}✅ .env created with secure secrets${NC}"
  else
    echo -e "${YELLOW}.env already exists, keeping existing configuration${NC}"
  fi
}

start_services() {
  echo -e "${CYAN}Starting Miau Finance services...${NC}"
  docker compose up -d
  echo ""
  echo -e "${CYAN}Waiting for services to become healthy...${NC}"
  sleep 15
  docker compose ps
}

print_summary() {
  echo ""
  echo -e "${GREEN}╱|、${NC}"
  echo -e "${GREEN} (˚ˎ 。7     Miau Finance ${MIAU_VERSION} is running!${NC}"
  echo -e "${GREEN}  |、˜〵${NC}"
  echo -e "${GREEN}  じしˍ,)ノ${NC}"
  echo ""
  echo -e "  ${CYAN}Terminal:${NC}    http://localhost:5173"
  echo -e "  ${CYAN}API:${NC}         http://localhost:8000/docs"
  echo -e "  ${CYAN}Grafana:${NC}     http://localhost:3000 (admin / \${GRAFANA_PASSWORD})"
  echo ""

  if curl -sf http://localhost:8000/api/v1/health > /dev/null 2>&1; then
    echo -e "  ${GREEN}✅ Backend is healthy${NC}"
  else
    echo -e "  ${YELLOW}⏳ Backend still starting... check 'docker compose logs backend'${NC}"
  fi
  echo ""
  echo -e "  Login: see DEMO_USERNAME / DEMO_PASSWORD in your .env (auto-generated)"
  echo -e "  Type  ${CYAN}help${NC} in the terminal for commands"
  echo ""
  echo -e "  ${YELLOW}🐟 Happy trading!${NC}"
}

# ── Main ──
echo ""
echo -e "${GREEN}╱|、${NC}"
echo -e "${GREEN} (˚ˎ 。7     Miau Finance Installer${NC}"
echo -e "${GREEN}  |、˜〵          ${MIAU_VERSION}${NC}"
echo -e "${GREEN}  じしˍ,)ノ${NC}"
echo ""

check_deps
clone_repo
setup_env
start_services
print_summary
